name: Sync Rolling

env:
  UPSTREAM_URL: "https://github.com/ros2/ros2_documentation.git"
  WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  UPSTREAM_BRANCH: "humble"
  DOWNSTREAM_BRANCH: "humble"
  FETCH_ARGS: ""
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "false" # "true" or "false"
on:
  workflow_dispatch:
    schedule:
      - cron: '0 0 * * *'
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Sync and merge Official PlanSys2 documentation
        uses: fmrico/sync-docs@v0.1.0
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}
